
# export ===========================================
model_cfg: null
checkpoint: null
output_dir: null

device: null
batch_size: null
width: null
height: null

model: null
backbone: null


# mmdeploy config ===================================
codebase_config: 
  with_argmax: false 

onnx_config: 
  save_file: 'ONNX.onnx'
  input_names: ['data']
  output_names: ['output']
  opset_version: 14

backend_config:
  fp16_mode: false

# tta ======================================================
tta:
  use: false
  augs: 
    HorizontalFlip: false
    VerticalFlip: false
    Rotate: 0
    Translate: 0,0