output_dir: null
load_from: null
data_root: null

# data =======================================================
dataset_type: labelme
classes: null
num_classes: null
img_suffix: '.bmp'
seg_map_suffix: '.json'

# rois ====================================================
rois: [[]]

# tta ======================================================
tta:
  use: false
  augs: 
    HorizontalFlip: false
    VerticalFlip: false
    Rotate: 0
    Translate: 0,0


# patch ===================================================
patch:
  use_patch: false
  include_point_positive: true
  centric: false
  sliding: false
  width: null
  height: null
  overlap_ratio: 0.2
  num_involved_pixel: 10
  sliding_bg_ratio: 0
  bg_ratio_by_image: 0
  bg_start_train_epoch_by_image: 0
  bg_start_val_epoch_by_image: 0
  translate: 0
  translate_range_width: 0
  translate_range_height: 0

# model ======================================================
model: null
backbone: null
height: null
width: null

# test =================================================================================
amp: True
resume: False
out: null
batch_size: 1

# etc. ===================================================
# wait_time: 2
# show: False

# custom hooks ==========================
custom_hooks:
  visualize_test:
    output_dir: null
    annotate: False
    contour_thres: 10
