output_dir: null
load_from: null
data_root: null

# data =======================================================
dataset_type: labelme
classes: null
num_classes: null
img_suffix: '.bmp'
seg_map_suffix: '.json'


# model ======================================================
model: 'mask2former'
backbone: 'swin_s'
height: 768
width: 1120

# test =================================================================================
amp: True
resume: False
out: null
batch_size: 1

# etc. ===================================================
tta: False
# wait_time: 2
# show: False

# custom hooks ==========================
custom_hooks:
  visualize_test:
    output_dir: /DeepLearning/etc/_athena_tests/recipes/agent/segmentation/mmseg/train_unit/m2f_patch/outputs/SEGMENTATION/250110/test/exp/vis
