output_dir: null
load_from: null
data_root: null

# data =======================================================
dataset_type: labelme
classes: null
num_classes: null
img_suffix: '.bmp'
seg_map_suffix: '.json'

# rois ====================================================
# rois: [[220, 60, 1340, 828]]
rois: [[]]

# patch ===================================================
patch:
  use_patch: true
  include_point_positive: null
  centric: null
  sliding: null
  width: 512
  height: 256
  overlap_ratio: 0.2
  num_involved_pixel: 10
  sliding_bg_ratio: null
  bg_ratio_by_image: null
  bg_start_train_epoch_by_image: null
  bg_start_val_epoch_by_image: null
  translate: null
  translate_range_width: null
  translate_range_height: null

# model ======================================================
model: null
backbone: null
height: null
width: null

# test =================================================================================
amp: True
resume: False
out: null
batch_size: 1

# etc. ===================================================
tta: False
# wait_time: 2
# show: False

# custom hooks ==========================
custom_hooks:
  visualize_test:
    output_dir: null
