output_dir: null
load_from: null
data_root: null

# data =======================================================
dataset_type: labelme
classes: null
num_classes: null
img_suffix: '.bmp'
seg_map_suffix: '.json'

rois: [[220, 60, 1340, 828]]

# model ======================================================
model: null
backbone: null
height: null
width: null

# test =================================================================================
amp: True
resume: False
out: null
batch_size: 1

# etc. ===================================================
tta: False
# wait_time: 2
# show: False

# custom hooks ==========================
custom_hooks:
  visualize_test:
    output_dir: null
