dataset_type: labelme
data_root: null
output_dir: null
load_from: null

# data =========================
classes: null
num_classes: 0
img_suffix: '.bmp'
seg_map_suffix: '.json'

# set crop-size/model-size =================================================================================
model: null
backbone: null
height: null
width: null

rois: [[]]

# patch ===================================================
patch:
  use_patch: false
  include_point_positive: true
  centric: false
  sliding: false
  width: null
  height: null
  overlap_ratio: 0.2
  num_involved_pixel: 10
  sliding_bg_ratio: 0
  bg_ratio_by_image: 0
  bg_start_train_epoch_by_image: 0
  bg_start_val_epoch_by_image: 0
  translate: 0
  translate_range_width: 0
  translate_range_height: 0

# train ================================
batch_size: 1
amp: True
epochs: 0
max_iters: 0
val_interval: 50

default_hooks:

# etc.
resume: False


# custom hooks ==========================
custom_hooks:
  visualize_val:
    freq_epoch: 1
    ratio: 0.5
    output_dir: null

  before_train:
    debug_dataloader:
      ratio: 0.5
      output_dir: null

  after_train_epoch:

  after_val_epoch:
  
  aiv:
    use: true
    logging: 
      output_dir: null

      monitor: 
        use: true 
        monitor_csv: true 
        monitor_figs: true 
        monitor_freq: 1

  checkpoint:
    interval: 1000
    by_epoch: false 
    save_best: 'mIoU'
    output_dir: null
    max_keep_ckpts: 2
